# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: follows.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='follows.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rfollows.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"B\n\x06\x46ollow\x12\x10\n\x08leaderid\x18\x01 \x01(\t\x12\x12\n\nfollowerid\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\x04\"I\n\x10GetFollowRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\"<\n\x11GetFollowResponse\x12\x0e\n\x06userid\x18\x01 \x03(\t\x12\x17\n\x0fnext_page_token\x18\x02 \x01(\t\";\n\x13\x43reateFollowRequest\x12\x10\n\x08leaderid\x18\x01 \x01(\t\x12\x12\n\nfollowerid\x18\x02 \x01(\t\";\n\x13\x44\x65leteFollowRequest\x12\x10\n\x08leaderid\x18\x01 \x01(\t\x12\x12\n\nfollowerid\x18\x02 \x01(\t2\x93\x03\n\rFollowService\x12X\n\x0cGetFollowers\x12\x11.GetFollowRequest\x1a\x12.GetFollowResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/users/{userid=*}/follows\x12X\n\x0cGetFollowees\x12\x11.GetFollowRequest\x1a\x12.GetFollowResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/users/{userid=*}/follows\x12\\\n\x0c\x43reateFollow\x12\x14.CreateFollowRequest\x1a\x07.Follow\"-\x82\xd3\xe4\x93\x02\'\"\x1b/users/{leaderid=*}/follows:\x08\x66ollower\x12p\n\x0c\x44\x65leteFollow\x12\x14.DeleteFollowRequest\x1a\x16.google.protobuf.Empty\"2\x82\xd3\xe4\x93\x02,**/users/{leaderid=*}/follows/{followerid=*}b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_FOLLOW = _descriptor.Descriptor(
  name='Follow',
  full_name='Follow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leaderid', full_name='Follow.leaderid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followerid', full_name='Follow.followerid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='Follow.created_at', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=142,
)


_GETFOLLOWREQUEST = _descriptor.Descriptor(
  name='GetFollowRequest',
  full_name='GetFollowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='GetFollowRequest.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='GetFollowRequest.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='GetFollowRequest.page_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=217,
)


_GETFOLLOWRESPONSE = _descriptor.Descriptor(
  name='GetFollowResponse',
  full_name='GetFollowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='GetFollowResponse.userid', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='GetFollowResponse.next_page_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=279,
)


_CREATEFOLLOWREQUEST = _descriptor.Descriptor(
  name='CreateFollowRequest',
  full_name='CreateFollowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leaderid', full_name='CreateFollowRequest.leaderid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followerid', full_name='CreateFollowRequest.followerid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=340,
)


_DELETEFOLLOWREQUEST = _descriptor.Descriptor(
  name='DeleteFollowRequest',
  full_name='DeleteFollowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leaderid', full_name='DeleteFollowRequest.leaderid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='followerid', full_name='DeleteFollowRequest.followerid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=401,
)

DESCRIPTOR.message_types_by_name['Follow'] = _FOLLOW
DESCRIPTOR.message_types_by_name['GetFollowRequest'] = _GETFOLLOWREQUEST
DESCRIPTOR.message_types_by_name['GetFollowResponse'] = _GETFOLLOWRESPONSE
DESCRIPTOR.message_types_by_name['CreateFollowRequest'] = _CREATEFOLLOWREQUEST
DESCRIPTOR.message_types_by_name['DeleteFollowRequest'] = _DELETEFOLLOWREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Follow = _reflection.GeneratedProtocolMessageType('Follow', (_message.Message,), {
  'DESCRIPTOR' : _FOLLOW,
  '__module__' : 'follows_pb2'
  # @@protoc_insertion_point(class_scope:Follow)
  })
_sym_db.RegisterMessage(Follow)

GetFollowRequest = _reflection.GeneratedProtocolMessageType('GetFollowRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFOLLOWREQUEST,
  '__module__' : 'follows_pb2'
  # @@protoc_insertion_point(class_scope:GetFollowRequest)
  })
_sym_db.RegisterMessage(GetFollowRequest)

GetFollowResponse = _reflection.GeneratedProtocolMessageType('GetFollowResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFOLLOWRESPONSE,
  '__module__' : 'follows_pb2'
  # @@protoc_insertion_point(class_scope:GetFollowResponse)
  })
_sym_db.RegisterMessage(GetFollowResponse)

CreateFollowRequest = _reflection.GeneratedProtocolMessageType('CreateFollowRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEFOLLOWREQUEST,
  '__module__' : 'follows_pb2'
  # @@protoc_insertion_point(class_scope:CreateFollowRequest)
  })
_sym_db.RegisterMessage(CreateFollowRequest)

DeleteFollowRequest = _reflection.GeneratedProtocolMessageType('DeleteFollowRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEFOLLOWREQUEST,
  '__module__' : 'follows_pb2'
  # @@protoc_insertion_point(class_scope:DeleteFollowRequest)
  })
_sym_db.RegisterMessage(DeleteFollowRequest)



_FOLLOWSERVICE = _descriptor.ServiceDescriptor(
  name='FollowService',
  full_name='FollowService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=404,
  serialized_end=807,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFollowers',
    full_name='FollowService.GetFollowers',
    index=0,
    containing_service=None,
    input_type=_GETFOLLOWREQUEST,
    output_type=_GETFOLLOWRESPONSE,
    serialized_options=b'\202\323\344\223\002\033\022\031/users/{userid=*}/follows',
  ),
  _descriptor.MethodDescriptor(
    name='GetFollowees',
    full_name='FollowService.GetFollowees',
    index=1,
    containing_service=None,
    input_type=_GETFOLLOWREQUEST,
    output_type=_GETFOLLOWRESPONSE,
    serialized_options=b'\202\323\344\223\002\033\022\031/users/{userid=*}/follows',
  ),
  _descriptor.MethodDescriptor(
    name='CreateFollow',
    full_name='FollowService.CreateFollow',
    index=2,
    containing_service=None,
    input_type=_CREATEFOLLOWREQUEST,
    output_type=_FOLLOW,
    serialized_options=b'\202\323\344\223\002\'\"\033/users/{leaderid=*}/follows:\010follower',
  ),
  _descriptor.MethodDescriptor(
    name='DeleteFollow',
    full_name='FollowService.DeleteFollow',
    index=3,
    containing_service=None,
    input_type=_DELETEFOLLOWREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=b'\202\323\344\223\002,**/users/{leaderid=*}/follows/{followerid=*}',
  ),
])
_sym_db.RegisterServiceDescriptor(_FOLLOWSERVICE)

DESCRIPTOR.services_by_name['FollowService'] = _FOLLOWSERVICE

# @@protoc_insertion_point(module_scope)
