# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import tweets_pb2 as tweets__pb2


class TweetServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTweet = channel.unary_unary(
                '/TweetService/CreateTweet',
                request_serializer=tweets__pb2.CreateTweetRequest.SerializeToString,
                response_deserializer=tweets__pb2.Tweet.FromString,
                )
        self.DeleteTweet = channel.unary_unary(
                '/TweetService/DeleteTweet',
                request_serializer=tweets__pb2.DeleteTweetRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetTweet = channel.unary_unary(
                '/TweetService/GetTweet',
                request_serializer=tweets__pb2.GetTweetRequest.SerializeToString,
                response_deserializer=tweets__pb2.Tweet.FromString,
                )


class TweetServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def CreateTweet(self, request, context):
        """Creates a new tweet
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTweet(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTweet(self, request, context):
        """Returns tweet given its ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TweetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTweet,
                    request_deserializer=tweets__pb2.CreateTweetRequest.FromString,
                    response_serializer=tweets__pb2.Tweet.SerializeToString,
            ),
            'DeleteTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTweet,
                    request_deserializer=tweets__pb2.DeleteTweetRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTweet,
                    request_deserializer=tweets__pb2.GetTweetRequest.FromString,
                    response_serializer=tweets__pb2.Tweet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TweetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TweetService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def CreateTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TweetService/CreateTweet',
            tweets__pb2.CreateTweetRequest.SerializeToString,
            tweets__pb2.Tweet.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TweetService/DeleteTweet',
            tweets__pb2.DeleteTweetRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TweetService/GetTweet',
            tweets__pb2.GetTweetRequest.SerializeToString,
            tweets__pb2.Tweet.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
