# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tweets.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tweets.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0ctweets.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"O\n\x05Tweet\x12\x0f\n\x07tweetid\x18\x01 \x01(\x04\x12\x0f\n\x07ownerid\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\x04\x12\x10\n\x08\x63ontents\x18\x04 \x01(\t\">\n\x12\x43reateTweetRequest\x12\x11\n\tcreatorid\x18\x01 \x01(\t\x12\x15\n\x05tweet\x18\x02 \x01(\x0b\x32\x06.Tweet\"%\n\x12\x44\x65leteTweetRequest\x12\x0f\n\x07tweetid\x18\x01 \x01(\t\"\"\n\x0fGetTweetRequest\x12\x0f\n\x07tweetid\x18\x01 \x01(\t2\xee\x01\n\x0cTweetService\x12\x42\n\x0b\x43reateTweet\x12\x13.CreateTweetRequest\x1a\x06.Tweet\"\x16\x82\xd3\xe4\x93\x02\x10\"\x07/tweets:\x05tweet\x12W\n\x0b\x44\x65leteTweet\x12\x13.DeleteTweetRequest\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/tweets/{tweetid=*}\x12\x41\n\x08GetTweet\x12\x10.GetTweetRequest\x1a\x06.Tweet\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/tweets/{tweetid=*}b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_TWEET = _descriptor.Descriptor(
  name='Tweet',
  full_name='Tweet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweetid', full_name='Tweet.tweetid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ownerid', full_name='Tweet.ownerid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='Tweet.created_at', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contents', full_name='Tweet.contents', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=154,
)


_CREATETWEETREQUEST = _descriptor.Descriptor(
  name='CreateTweetRequest',
  full_name='CreateTweetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='creatorid', full_name='CreateTweetRequest.creatorid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tweet', full_name='CreateTweetRequest.tweet', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=218,
)


_DELETETWEETREQUEST = _descriptor.Descriptor(
  name='DeleteTweetRequest',
  full_name='DeleteTweetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweetid', full_name='DeleteTweetRequest.tweetid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=257,
)


_GETTWEETREQUEST = _descriptor.Descriptor(
  name='GetTweetRequest',
  full_name='GetTweetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tweetid', full_name='GetTweetRequest.tweetid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=293,
)

_CREATETWEETREQUEST.fields_by_name['tweet'].message_type = _TWEET
DESCRIPTOR.message_types_by_name['Tweet'] = _TWEET
DESCRIPTOR.message_types_by_name['CreateTweetRequest'] = _CREATETWEETREQUEST
DESCRIPTOR.message_types_by_name['DeleteTweetRequest'] = _DELETETWEETREQUEST
DESCRIPTOR.message_types_by_name['GetTweetRequest'] = _GETTWEETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tweet = _reflection.GeneratedProtocolMessageType('Tweet', (_message.Message,), {
  'DESCRIPTOR' : _TWEET,
  '__module__' : 'tweets_pb2'
  # @@protoc_insertion_point(class_scope:Tweet)
  })
_sym_db.RegisterMessage(Tweet)

CreateTweetRequest = _reflection.GeneratedProtocolMessageType('CreateTweetRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETWEETREQUEST,
  '__module__' : 'tweets_pb2'
  # @@protoc_insertion_point(class_scope:CreateTweetRequest)
  })
_sym_db.RegisterMessage(CreateTweetRequest)

DeleteTweetRequest = _reflection.GeneratedProtocolMessageType('DeleteTweetRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETETWEETREQUEST,
  '__module__' : 'tweets_pb2'
  # @@protoc_insertion_point(class_scope:DeleteTweetRequest)
  })
_sym_db.RegisterMessage(DeleteTweetRequest)

GetTweetRequest = _reflection.GeneratedProtocolMessageType('GetTweetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTWEETREQUEST,
  '__module__' : 'tweets_pb2'
  # @@protoc_insertion_point(class_scope:GetTweetRequest)
  })
_sym_db.RegisterMessage(GetTweetRequest)



_TWEETSERVICE = _descriptor.ServiceDescriptor(
  name='TweetService',
  full_name='TweetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=296,
  serialized_end=534,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateTweet',
    full_name='TweetService.CreateTweet',
    index=0,
    containing_service=None,
    input_type=_CREATETWEETREQUEST,
    output_type=_TWEET,
    serialized_options=b'\202\323\344\223\002\020\"\007/tweets:\005tweet',
  ),
  _descriptor.MethodDescriptor(
    name='DeleteTweet',
    full_name='TweetService.DeleteTweet',
    index=1,
    containing_service=None,
    input_type=_DELETETWEETREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=b'\202\323\344\223\002\025*\023/tweets/{tweetid=*}',
  ),
  _descriptor.MethodDescriptor(
    name='GetTweet',
    full_name='TweetService.GetTweet',
    index=2,
    containing_service=None,
    input_type=_GETTWEETREQUEST,
    output_type=_TWEET,
    serialized_options=b'\202\323\344\223\002\025\022\023/tweets/{tweetid=*}',
  ),
])
_sym_db.RegisterServiceDescriptor(_TWEETSERVICE)

DESCRIPTOR.services_by_name['TweetService'] = _TWEETSERVICE

# @@protoc_insertion_point(module_scope)
