# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timelines.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
import tweets_pb2 as tweets__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='timelines.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0ftimelines.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x0ctweets.proto\"J\n\x11ListTweetsRequest\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x12\n\npage_token\x18\x03 \x01(\t\"K\n\x08Timeline\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x16\n\x06tweets\x18\x02 \x03(\x0b\x32\x06.Tweet\x12\x17\n\x0fnext_page_token\x18\x03 \x01(\t2\xb2\x01\n\x0fTimelineService\x12M\n\nListTweets\x12\x12.ListTweetsRequest\x1a\t.Timeline\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/users/{userid=*}/tweets\x12P\n\x0bGetTimeline\x12\x12.ListTweetsRequest\x1a\t.Timeline\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/users/{userid=*}/timelineb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,tweets__pb2.DESCRIPTOR,])




_LISTTWEETSREQUEST = _descriptor.Descriptor(
  name='ListTweetsRequest',
  full_name='ListTweetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='ListTweetsRequest.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='ListTweetsRequest.page_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_token', full_name='ListTweetsRequest.page_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=137,
)


_TIMELINE = _descriptor.Descriptor(
  name='Timeline',
  full_name='Timeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='Timeline.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tweets', full_name='Timeline.tweets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_page_token', full_name='Timeline.next_page_token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=214,
)

_TIMELINE.fields_by_name['tweets'].message_type = tweets__pb2._TWEET
DESCRIPTOR.message_types_by_name['ListTweetsRequest'] = _LISTTWEETSREQUEST
DESCRIPTOR.message_types_by_name['Timeline'] = _TIMELINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListTweetsRequest = _reflection.GeneratedProtocolMessageType('ListTweetsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTTWEETSREQUEST,
  '__module__' : 'timelines_pb2'
  # @@protoc_insertion_point(class_scope:ListTweetsRequest)
  })
_sym_db.RegisterMessage(ListTweetsRequest)

Timeline = _reflection.GeneratedProtocolMessageType('Timeline', (_message.Message,), {
  'DESCRIPTOR' : _TIMELINE,
  '__module__' : 'timelines_pb2'
  # @@protoc_insertion_point(class_scope:Timeline)
  })
_sym_db.RegisterMessage(Timeline)



_TIMELINESERVICE = _descriptor.ServiceDescriptor(
  name='TimelineService',
  full_name='TimelineService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=217,
  serialized_end=395,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListTweets',
    full_name='TimelineService.ListTweets',
    index=0,
    containing_service=None,
    input_type=_LISTTWEETSREQUEST,
    output_type=_TIMELINE,
    serialized_options=b'\202\323\344\223\002\032\022\030/users/{userid=*}/tweets',
  ),
  _descriptor.MethodDescriptor(
    name='GetTimeline',
    full_name='TimelineService.GetTimeline',
    index=1,
    containing_service=None,
    input_type=_LISTTWEETSREQUEST,
    output_type=_TIMELINE,
    serialized_options=b'\202\323\344\223\002\034\022\032/users/{userid=*}/timeline',
  ),
])
_sym_db.RegisterServiceDescriptor(_TIMELINESERVICE)

DESCRIPTOR.services_by_name['TimelineService'] = _TIMELINESERVICE

# @@protoc_insertion_point(module_scope)
